### ISSUE TITLE
Message needs to support higher content sizes.

### ISSUE THREAD

**Issue by rpk7524** [ithunt/asksg#9]
Default for string is varchar(255), we need to support longer messages (particularly for email, reddit, and facebook).

Caused by: org.springframework.orm.jpa.JpaSystemException: org.hibernate.exception.DataException: Data truncation: Data too long for column 'content' at row 1;nested exception is javax.persistence.PersistenceException: org.hibernate.exception.DataException: Data truncation: Data too long for column 'content' at row 1
        at $Proxy46.save(Unknown Source)
        at edu.rit.asksg.service.MessageServiceImpl.saveMessage(MessageServiceImpl.java:48)
        at edu.rit.asksg.service.ConversationServiceImpl.saveConversation(ConversationServiceImpl.java:24)
        at edu.rit.asksg.domain.Email.receive(Email.java:126)

Also, please write unit tests to demonstrate this issue has been fixed.

**Comment by dge9788** [comment]
probably needs to be a blob...
